# Generated by Django 4.1.7 on 2023-03-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='problem_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='grades.problemset'),
            preserve_default=False,
        ),
    ]
